services:
  agent_service:
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    ports:
      - "8080:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
      - LANGCHAIN_VERBOSE=true
      - LANGCHAIN_DEBUG=true
      - LANGGRAPH_DEBUG=true
    develop:
      watch:
        - path: src/agents/
          action: sync+restart
          target: /app/agents/
        - path: src/schema/
          action: sync+restart
          target: /app/schema/
        - path: src/service/
          action: sync+restart
          target: /app/service/
    logging:
      driver: json-file

  streamlit_app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8501:8501"
    depends_on:
      - agent_service
    environment:
      - AGENT_URL=http://agent_service:8000
      - PYTHONUNBUFFERED=1
      - STREAMLIT_LOG_LEVEL=debug
      - LOG_LEVEL=DEBUG
    develop:
      watch:
        - path: src/client/
          action: sync+restart
          target: /app/client/
        - path: src/schema/
          action: sync+restart
          target: /app/schema/
        - path: src/streamlit_app.py
          action: sync+restart
          target: /app/streamlit_app.py
    logging:
      driver: json-file

  # test:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.test
  #   volumes:
  #     - ./src:/app/src
  #     - ./tests:/app/tests
  #   environment:
  #     - PYTHONPATH=/app
  #     - OPENAI_API_KEY=sk-fake-openai-key
